namespace Logistics.Shared.Models;

public record PaymentLinkDto
{
    public Guid Id { get; set; }
    public required string Token { get; set; }
    public Guid InvoiceId { get; set; }
    public DateTime ExpiresAt { get; set; }
    public bool IsActive { get; set; }
    public Guid CreatedByUserId { get; set; }
    public int AccessCount { get; set; }
    public DateTime? LastAccessedAt { get; set; }
    public bool IsValid { get; set; }
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// The full URL for the payment link (generated by the API).
    /// </summary>
    public string? Url { get; set; }
}
