// @ts-check
import { defineConfig } from "eslint/config";
import rootConfig from "../../eslint.config.js";

export default defineConfig([
  {
    // Vendored upstream code — not ours to lint.
    //
    // ui/primitives/** is Helm (spartan) source, regenerated by `ng g @spartan-ng/cli:ui` and
    // re-normalized by tools/normalize-helm.mjs. It uses `hlm-*` / `brn-*` selectors and aliased
    // inputs (@angular-eslint/no-input-rename) that are upstream's public API. Linting it would
    // invite "fixes" that fork us off upstream and get clobbered on the next regen.
    //
    // api/generated/** is the ng-openapi-gen client. Every file carries an `/* eslint-disable */`
    // header, which is what produced the ~381 "unused eslint-disable directive" warnings. The repo
    // convention (.claude/rules/code-quality.md) is that generated files are exempt from lint.
    ignores: ["**/ui/primitives/**", "**/api/generated/**"],
  },
  ...rootConfig,
  {
    files: ["**/*.ts"],
    rules: {
      "@angular-eslint/directive-selector": [
        "error",
        {
          type: "attribute",
          prefix: "ui",
          style: "camelCase",
        },
      ],
      "@angular-eslint/component-selector": [
        "error",
        {
          // "element" alone is not enough: UiSortHeader is an @Component with the attribute
          // selector `th[uiSortHeader]`, so the rule must accept attribute selectors too.
          type: ["element", "attribute"],
          prefix: "ui",
          style: "kebab-case",
        },
      ],
    },
  },
  {
    // The rule applies one `style` to every selector type it accepts, so the entry above demands
    // kebab-case of attribute selectors too — and `th[uiSortHeader]` is camelCase, as an attribute
    // selector should be. There is no way to say "kebab-case for elements, camelCase for
    // attributes" in a single entry, so the one attribute-selector @Component in the library gets
    // its own. Add files here if more appear; a new one will fail the kebab-case check first.
    files: ["**/ui/table/sort-header.ts"],
    rules: {
      "@angular-eslint/component-selector": [
        "error",
        {
          type: "attribute",
          prefix: "ui",
          style: "camelCase",
        },
      ],
    },
  },
  {
    files: ["**/*.html"],
    rules: {},
  },
]);
