global using AutoMapper;
global using MediatR;
global using Logistics.Application.Contracts;
global using Logistics.Application.Contracts.Commands;
global using Logistics.Application.Contracts.Models;
global using Logistics.Application.Contracts.Queries;
global using Logistics.Domain.Entities;
global using Logistics.Domain.Repositories;
global using Logistics.Domain.Specifications;