using Logistics.Domain.Entities;
using Logistics.Shared.Models;
using Riok.Mapperly.Abstractions;

namespace Logistics.Mappings;

[Mapper]
public static partial class DocumentMapper
{
    // Base -> DTO (polymorphic dispatcher; not generated)
    // Note: DeliveryDocument must be checked before LoadDocument since it derives from LoadDocument
    public static DocumentDto ToDto(this Document src)
    {
        return src switch
        {
            DeliveryDocument dd => dd.ToDeliveryDocumentDto(),
            LoadDocument ld => ld.ToLoadDocumentDto(),
            EmployeeDocument ed => ed.ToEmployeeDocumentDto(),
            TruckDocument td => td.ToTruckDocumentDto(),
            _ => throw new NotSupportedException($"Unsupported document type: {src.GetType().Name}")
        };
    }

    // Collection helpers (use the polymorphic dispatcher)
    public static IEnumerable<DocumentDto> ToDto(this IEnumerable<Document> src) => src.Select(ToDto);

    // Derived -> DTO (generated by Mapperly)
    // Map DeliveryDocument (includes LoadId from parent and all POD/BOL metadata)
    [MapProperty(nameof(DeliveryDocument.LoadId), nameof(DocumentDto.LoadId))]
    private static partial DocumentDto ToDeliveryDocumentDto(this DeliveryDocument src);

    // Derived -> DTO (generated by Mapperly)
    // Map LoadDocument.LoadId -> DocumentDto.LoadId
    [MapProperty(nameof(LoadDocument.LoadId), nameof(DocumentDto.LoadId))]
    private static partial DocumentDto ToLoadDocumentDto(this LoadDocument src);

    // Derived -> DTO (generated by Mapperly)
    // Map EmployeeDocument.EmployeeId -> DocumentDto.EmployeeId
    [MapProperty(nameof(EmployeeDocument.EmployeeId), nameof(DocumentDto.EmployeeId))]
    private static partial DocumentDto ToEmployeeDocumentDto(this EmployeeDocument src);

    // Derived -> DTO (generated by Mapperly)
    // Map TruckDocument.TruckId -> DocumentDto.TruckId
    [MapProperty(nameof(TruckDocument.TruckId), nameof(DocumentDto.TruckId))]
    private static partial DocumentDto ToTruckDocumentDto(this TruckDocument src);

    private static DateTime Map(DateTimeOffset value) => value.UtcDateTime;

    private static DateTime? Map(DateTimeOffset? value) => value?.UtcDateTime;
}
