global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Logistics.DriverApp.Authentication;
global using Logistics.DriverApp.Helpers;
global using Logistics.DriverApp.Views;
global using Logistics.DriverApp.ViewModels;
global using Logistics.Sdk;
global using Logistics.Sdk.Models;
global using Logistics.Shared;