import {
  lucideArrowDown,
  lucideArrowLeft,
  lucideArrowRight,
  lucideArrowUp,
  lucideBan,
  lucideBanknote,
  lucideBell,
  lucideBellOff,
  lucideBook,
  lucideBot,
  lucideBox,
  lucideBriefcase,
  lucideBuilding2,
  lucideCalculator,
  lucideCalendar,
  lucideCalendarX,
  lucideCar,
  lucideChartColumn,
  lucideChartLine,
  lucideChartPie,
  lucideCheck,
  lucideCheckSquare,
  lucideChevronDown,
  lucideChevronLeft,
  lucideChevronRight,
  lucideChevronsLeft,
  lucideChevronsRight,
  lucideChevronsUpDown,
  lucideChevronUp,
  lucideCircle,
  lucideCircleAlert,
  lucideCircleCheck,
  lucideCircleHelp,
  lucideCircleMinus,
  lucideCirclePlus,
  lucideCircleX,
  lucideClipboard,
  lucideClock,
  lucideCloud,
  lucideCompass,
  lucideCopy,
  lucideCreditCard,
  lucideDollarSign,
  lucideDownload,
  lucideEllipsisVertical,
  lucideExternalLink,
  lucideEye,
  lucideEyeOff,
  lucideFile,
  lucideFileCheck,
  lucideFileInput,
  lucideFileOutput,
  lucideFilePen,
  lucideFilePenLine,
  lucideFileText,
  lucideFilter,
  lucideFilterX,
  lucideFlag,
  lucideFolder,
  lucideFolderOpen,
  lucideFuel,
  lucideGauge,
  lucideGlobe,
  lucideHeart,
  lucideHistory,
  lucideHome,
  lucideHouse,
  lucideIdCard,
  lucideImage,
  lucideImages,
  lucideInbox,
  lucideInfo,
  lucideKey,
  lucideLayoutGrid,
  lucideLightbulb,
  lucideLink,
  lucideList,
  lucideLoaderCircle,
  lucideLock,
  lucideLogIn,
  lucideLogOut,
  lucideMail,
  lucideMap,
  lucideMapPin,
  lucideMenu,
  lucideMessageSquare,
  lucideMessagesSquare,
  lucideMinus,
  lucideMoon,
  lucideMoveHorizontal,
  lucideNavigation,
  lucidePackage,
  lucidePauseCircle,
  lucidePawPrint,
  lucidePencil,
  lucidePercent,
  lucidePhone,
  lucidePlay,
  lucidePlus,
  lucideReceipt,
  lucideRefreshCw,
  lucideRoute,
  lucideSave,
  lucideSearch,
  lucideSend,
  lucideServer,
  lucideSettings,
  lucideShield,
  lucideShieldCheck,
  lucideShoppingCart,
  lucideSlidersHorizontal,
  lucideSmartphone,
  lucideSnowflake,
  lucideSparkles,
  lucideSquarePen,
  lucideStar,
  lucideStopCircle,
  lucideSun,
  lucideTable,
  lucideTag,
  lucideTrash,
  lucideTrendingUp,
  lucideTriangleAlert,
  lucideTrophy,
  lucideTruck,
  lucideUndo,
  lucideUpload,
  lucideUser,
  lucideUserMinus,
  lucideUserPen,
  lucideUserPlus,
  lucideUsers,
  lucideWallet,
  lucideWarehouse,
  lucideWifi,
  lucideWifiOff,
  lucideWrench,
  lucideX,
  lucideZap,
  lucideZoomIn,
} from "@ng-icons/lucide";
import { brandFacebook, brandLinkedin, brandX } from "./brand-icons";

/**
 * Every icon the app can render, keyed by its canonical lucide (or hand-vendored `brand-*`) kebab
 * name. A name outside this record is a compile error at `<ui-icon name="...">` — which is the
 * whole point: an unmapped icon used to render a silently blank <svg>.
 *
 * To add an icon: import its `@ng-icons/lucide` export and add one alphabetically-sorted entry.
 */
export const UI_ICONS = {
  "arrow-down": lucideArrowDown,
  "arrow-left": lucideArrowLeft,
  "arrow-right": lucideArrowRight,
  "arrow-up": lucideArrowUp,
  ban: lucideBan,
  banknote: lucideBanknote,
  bell: lucideBell,
  "bell-off": lucideBellOff,
  book: lucideBook,
  bot: lucideBot,
  box: lucideBox,
  "brand-facebook": brandFacebook,
  "brand-linkedin": brandLinkedin,
  "brand-x": brandX,
  briefcase: lucideBriefcase,
  "building-2": lucideBuilding2,
  calculator: lucideCalculator,
  calendar: lucideCalendar,
  "calendar-x": lucideCalendarX,
  car: lucideCar,
  "chart-column": lucideChartColumn,
  "chart-line": lucideChartLine,
  "chart-pie": lucideChartPie,
  check: lucideCheck,
  "check-square": lucideCheckSquare,
  "chevron-down": lucideChevronDown,
  "chevron-left": lucideChevronLeft,
  "chevron-right": lucideChevronRight,
  "chevron-up": lucideChevronUp,
  "chevrons-left": lucideChevronsLeft,
  "chevrons-right": lucideChevronsRight,
  "chevrons-up-down": lucideChevronsUpDown,
  circle: lucideCircle,
  "circle-alert": lucideCircleAlert,
  "circle-check": lucideCircleCheck,
  "circle-help": lucideCircleHelp,
  "circle-minus": lucideCircleMinus,
  "circle-plus": lucideCirclePlus,
  "circle-x": lucideCircleX,
  clipboard: lucideClipboard,
  clock: lucideClock,
  cloud: lucideCloud,
  compass: lucideCompass,
  copy: lucideCopy,
  "credit-card": lucideCreditCard,
  "dollar-sign": lucideDollarSign,
  download: lucideDownload,
  "ellipsis-vertical": lucideEllipsisVertical,
  "external-link": lucideExternalLink,
  eye: lucideEye,
  "eye-off": lucideEyeOff,
  file: lucideFile,
  "file-check": lucideFileCheck,
  "file-input": lucideFileInput,
  "file-output": lucideFileOutput,
  "file-pen": lucideFilePen,
  "file-pen-line": lucideFilePenLine,
  "file-text": lucideFileText,
  filter: lucideFilter,
  "filter-x": lucideFilterX,
  flag: lucideFlag,
  folder: lucideFolder,
  "folder-open": lucideFolderOpen,
  fuel: lucideFuel,
  gauge: lucideGauge,
  globe: lucideGlobe,
  heart: lucideHeart,
  history: lucideHistory,
  home: lucideHome,
  house: lucideHouse,
  "id-card": lucideIdCard,
  image: lucideImage,
  images: lucideImages,
  inbox: lucideInbox,
  info: lucideInfo,
  key: lucideKey,
  "layout-grid": lucideLayoutGrid,
  lightbulb: lucideLightbulb,
  link: lucideLink,
  list: lucideList,
  "loader-circle": lucideLoaderCircle,
  lock: lucideLock,
  "log-in": lucideLogIn,
  "log-out": lucideLogOut,
  mail: lucideMail,
  map: lucideMap,
  "map-pin": lucideMapPin,
  menu: lucideMenu,
  "message-square": lucideMessageSquare,
  "messages-square": lucideMessagesSquare,
  minus: lucideMinus,
  moon: lucideMoon,
  "move-horizontal": lucideMoveHorizontal,
  navigation: lucideNavigation,
  package: lucidePackage,
  "pause-circle": lucidePauseCircle,
  "paw-print": lucidePawPrint,
  pencil: lucidePencil,
  percent: lucidePercent,
  phone: lucidePhone,
  play: lucidePlay,
  plus: lucidePlus,
  receipt: lucideReceipt,
  "refresh-cw": lucideRefreshCw,
  route: lucideRoute,
  save: lucideSave,
  search: lucideSearch,
  send: lucideSend,
  server: lucideServer,
  settings: lucideSettings,
  shield: lucideShield,
  "shield-check": lucideShieldCheck,
  "shopping-cart": lucideShoppingCart,
  "sliders-horizontal": lucideSlidersHorizontal,
  smartphone: lucideSmartphone,
  snowflake: lucideSnowflake,
  sparkles: lucideSparkles,
  "square-pen": lucideSquarePen,
  star: lucideStar,
  "stop-circle": lucideStopCircle,
  sun: lucideSun,
  table: lucideTable,
  tag: lucideTag,
  trash: lucideTrash,
  "trending-up": lucideTrendingUp,
  "triangle-alert": lucideTriangleAlert,
  trophy: lucideTrophy,
  truck: lucideTruck,
  undo: lucideUndo,
  upload: lucideUpload,
  user: lucideUser,
  "user-minus": lucideUserMinus,
  "user-pen": lucideUserPen,
  "user-plus": lucideUserPlus,
  users: lucideUsers,
  wallet: lucideWallet,
  warehouse: lucideWarehouse,
  wifi: lucideWifi,
  "wifi-off": lucideWifiOff,
  wrench: lucideWrench,
  x: lucideX,
  zap: lucideZap,
  "zoom-in": lucideZoomIn,
} as const;

/** Every name `<ui-icon>` accepts. The 51 files that import `IconName` key off this. */
export type IconName = keyof typeof UI_ICONS;

/** Rendered when a dynamic name does not resolve — visibly wrong beats silently blank. */
export const ERROR_ICON_SVG = UI_ICONS["circle-alert"];
