/**
 * Maps the legacy PrimeIcons-style names `ui-icon` receives (`pi-` prefix stripped) onto
 * lucide icon names (kebab-case, as `@lucide/angular`'s dynamic loader expects). Lets the
 * 80+ existing `<ui-icon name="...">` call sites keep their names while rendering lucide
 * SVGs. Phase 6 can migrate call sites to lucide names directly.
 *
 * `@lucide/angular` is the single lucide runtime (it also backs the nav's dynamic icons);
 * its `LucideDynamicIcon` loads any icon by name, so nothing here needs registering.
 */
export const PI_TO_LUCIDE: Record<string, string> = {
  "check-circle": "circle-check",
  box: "box",
  truck: "truck",
  "map-marker": "map-pin",
  "map-pin": "map-pin",
  "exclamation-triangle": "triangle-alert",
  user: "user",
  users: "users",
  "exclamation-circle": "circle-alert",
  "alert-circle": "circle-alert",
  check: "check",
  "info-circle": "info",
  info: "info",
  file: "file",
  "id-card": "id-card",
  comment: "message-square",
  comments: "messages-square",
  tag: "tag",
  clock: "clock",
  times: "x",
  "times-circle": "circle-x",
  inbox: "inbox",
  flag: "flag",
  dollar: "dollar-sign",
  building: "building-2",
  map: "map",
  link: "link",
  image: "image",
  images: "images",
  folder: "folder",
  "folder-open": "folder-open",
  "external-link": "external-link",
  "credit-card": "credit-card",
  car: "car",
  minus: "minus",
  "minus-circle": "circle-minus",
  lock: "lock",
  "file-edit": "file-pen",
  "file-pdf": "file-text",
  "file-invoice": "file-text",
  "file-check": "file-check",
  circle: "circle",
  "chart-line": "chart-line",
  "chart-bar": "chart-column",
  bolt: "zap",
  wallet: "wallet",
  "user-plus": "user-plus",
  upload: "upload",
  trophy: "trophy",
  "star-fill": "star",
  sparkles: "sparkles",
  send: "send",
  "search-plus": "zoom-in",
  receipt: "receipt",
  question: "circle-help",
  "plus-circle": "circle-plus",
  phone: "phone",
  package: "package",
  history: "history",
  globe: "globe",
  directions: "navigation",
  clipboard: "clipboard",
  "chevron-right": "chevron-right",
  "angle-right": "chevron-right",
  calendar: "calendar",
  briefcase: "briefcase",
  "bell-slash": "bell-off",
  "arrows-h": "move-horizontal",
  "arrow-right": "arrow-right",
  sun: "sun",
  moon: "moon",
  eye: "eye",
  "eye-slash": "eye-off",
};

/** Fallback rendered when a name is not mapped. */
export const UI_ICON_FALLBACK = "circle";
