using Logistics.Domain.Core;
using Logistics.Domain.ValueObjects;
using Logistics.Shared.Consts;

namespace Logistics.Domain.Entities;

public class Employee : Entity, ITenantEntity
{
    public string? Email { get; set; }
    public string? FirstName { get; set; }
    public string? LastName { get; set; }
    public string? PhoneNumber { get; set; }
    
    public required Money Salary { get; set; }
    public SalaryType SalaryType { get; set; }
    
    /// <summary>
    /// When employee joined to this tenant
    /// </summary>
    public DateTime JoinedDate { get; set; } = DateTime.UtcNow;
    
    /// <summary>
    /// User's device token generated by the Firebase
    /// </summary>
    public string? DeviceToken { get; set; }
    
    public string? TruckId { get; set; }
    public virtual Truck? Truck { get; set; }

    /// <summary>
    /// Dispatched loads by dispatchers
    /// </summary>
    public virtual List<Load> DispatchedLoads { get; } = [];
    public virtual List<PayrollInvoice> PayrollInvoices { get; set; } = [];

    /// <summary>
    /// User tenant roles
    /// </summary>
    public virtual HashSet<TenantRole> Roles { get; } = new(new TenantRoleComparer());

    public virtual List<EmployeeTenantRole> EmployeeRoles { get; } = [];

    public string GetFullName() => $"{FirstName} {LastName}";

    public static Employee CreateEmployeeFromUser(
        User user, 
        decimal salary = 0, 
        SalaryType salaryType = SalaryType.None)
    {
        var newEmployee = new Employee
        {
            Id = user.Id,
            Email = user.Email,
            FirstName = user.FirstName,
            LastName = user.LastName,
            PhoneNumber = user.PhoneNumber,
            Salary = salary,
            SalaryType = salaryType
        };

        return newEmployee;
    }
}
