using Logistics.API.Extensions;
using Logistics.Domain.Primitives.Enums;
using Logistics.Shared.Identity.Roles;
using Logistics.Shared.Models;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Logistics.Application.Modules.Compliance.Privacy.Commands;
using Logistics.Application.Modules.Compliance.Privacy.Queries;

namespace Logistics.API.Controllers;

/// <summary>
///     GDPR data subject rights — data export, account deletion, cookie consent.
/// </summary>
[ApiController]
[Route("privacy")]
[Produces("application/json")]
public class PrivacyController(IMediator mediator) : ControllerBase
{
    /// <summary>
    ///     Request a personal data export. The ZIP is generated by a background
    ///     job and the user is emailed a portal link when it is ready.
    /// </summary>
    [HttpPost("exports", Name = "RequestDataExport")]
    [ProducesResponseType(typeof(Guid), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status400BadRequest)]
    [Authorize]
    public async Task<IActionResult> RequestExport()
    {
        var result = await mediator.Send(new RequestDataExportCommand());
        return result.IsSuccess ? Ok(result.Value) : BadRequest(ErrorResponse.FromResult(result));
    }

    /// <summary>
    ///     List the current user's data export requests.
    /// </summary>
    [HttpGet("exports", Name = "GetMyDataExports")]
    [ProducesResponseType(typeof(List<DataExportRequestDto>), StatusCodes.Status200OK)]
    [Authorize]
    public async Task<IActionResult> GetMyExports()
    {
        var result = await mediator.Send(new GetMyDataExportsQuery());
        return Ok(result.Value);
    }

    /// <summary>
    ///     Fetch a single data export request, including a freshly-signed download URL
    ///     when the export is Ready and the blob has not expired.
    /// </summary>
    [HttpGet("exports/{id:guid}", Name = "GetDataExportRequest")]
    [ProducesResponseType(typeof(DataExportRequestDto), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status404NotFound)]
    [Authorize]
    public async Task<IActionResult> GetExport(Guid id)
    {
        var result = await mediator.Send(new GetDataExportRequestQuery { Id = id });
        return result.IsSuccess ? Ok(result.Value) : NotFound(ErrorResponse.FromResult(result));
    }

    /// <summary>
    ///     Schedule the current user's account for deletion. A 30-day grace period applies;
    ///     the request can be cancelled until anonymization runs.
    /// </summary>
    [HttpPost("deletions", Name = "RequestDataDeletion")]
    [ProducesResponseType(typeof(Guid), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status400BadRequest)]
    [Authorize]
    public async Task<IActionResult> RequestDeletion([FromBody] RequestDataDeletionCommand request)
    {
        var result = await mediator.Send(request);
        return result.IsSuccess ? Ok(result.Value) : BadRequest(ErrorResponse.FromResult(result));
    }

    /// <summary>
    ///     Cancel a pending deletion request within its grace period.
    /// </summary>
    [HttpDelete("deletions/{id:guid}", Name = "CancelDataDeletion")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status400BadRequest)]
    [Authorize]
    public async Task<IActionResult> CancelDeletion(Guid id)
    {
        var result = await mediator.Send(new CancelDataDeletionCommand { Id = id });
        return result.IsSuccess ? NoContent() : BadRequest(ErrorResponse.FromResult(result));
    }

    /// <summary>
    ///     List the current user's deletion requests (history + any pending cancellable one).
    /// </summary>
    [HttpGet("deletions", Name = "GetMyDataDeletions")]
    [ProducesResponseType(typeof(List<DataDeletionRequestDto>), StatusCodes.Status200OK)]
    [Authorize]
    public async Task<IActionResult> GetMyDeletions()
    {
        var result = await mediator.Send(new GetMyDataDeletionsQuery());
        return Ok(result.Value);
    }

    /// <summary>
    ///     Record a cookie / processing consent decision for the current authenticated user.
    /// </summary>
    [HttpPost("consent", Name = "RecordConsent")]
    [ProducesResponseType(typeof(Guid), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status400BadRequest)]
    [Authorize]
    public async Task<IActionResult> RecordConsent([FromBody] RecordConsentRequest body)
    {
        var command = new RecordConsentCommand
        {
            UserId = User.GetUserId()!.Value,
            ConsentType = body.ConsentType,
            Granted = body.Granted,
            IpAddress = HttpContext.Connection.RemoteIpAddress?.ToString(),
            UserAgent = Request.Headers.UserAgent.ToString()
        };

        var result = await mediator.Send(command);
        return result.IsSuccess ? Ok(result.Value) : BadRequest(ErrorResponse.FromResult(result));
    }

    /// <summary>
    ///     The current user's full consent history.
    /// </summary>
    [HttpGet("consent/history", Name = "GetConsentHistory")]
    [ProducesResponseType(typeof(List<ConsentRecordDto>), StatusCodes.Status200OK)]
    [Authorize]
    public async Task<IActionResult> GetConsentHistory()
    {
        var result = await mediator.Send(new GetConsentHistoryQuery());
        return Ok(result.Value);
    }

    /// <summary>
    ///     Admin overview of all pending data exports and deletion requests across tenants.
    /// </summary>
    [HttpGet("admin/requests", Name = "GetPendingDataRequests")]
    [ProducesResponseType(typeof(PendingDataRequestsDto), StatusCodes.Status200OK)]
    [Authorize(Roles = $"{AppRoles.SuperAdmin},{AppRoles.Admin}")]
    public async Task<IActionResult> GetPendingRequests()
    {
        var result = await mediator.Send(new GetPendingDataRequestsQuery());
        return Ok(result.Value);
    }
}

/// <summary>
///     Body for the consent endpoint — UserId is taken from the auth context.
/// </summary>
public record RecordConsentRequest(ConsentType ConsentType, bool Granted);
